name: CI
on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22

      - name: Show flake
        run: nix flake show

      - name: Check flake
        run: nix flake check

  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v22

      - uses: ./
        id: attic
        with:
          server: https://attic.alxandr.me/attic/
          cacheName: yolodev
          token: ${{ secrets.ATTIC_TOKEN }}

      - name: Build
        run: nix build .#devShells.x86_64-linux.default --accept-flake-config
